architecture-beta
    group sources(cloud)[Data Sources]
    group collection(server)[Collection Layer]
    group transport(disk)[Transport Layer]
    group processing(cogs)[Processing Layer]
    group persistence(database)[Persistence Layer]
    group enforcement(shield)[Enforcement Layer]

    service validation(server)[Validation Service] in sources
    service bookstore(server)[Book Store] in sources
    service kafka_validation(disk)[Kafka Validation] in transport
    service kafka_journey(disk)[Kafka Journey] in transport
    service worker(cogs)[Naglfar Worker] in processing
    service analytics(cogs)[Analytics Worker] in processing
    service neo4j(database)[Neo4j] in persistence
    service redis(database)[Redis] in persistence
    service enforcer(shield)[Validation Service] in enforcement

    validation:B --> T:kafka_validation
    bookstore:B --> T:kafka_journey
    kafka_validation:R --> L:worker
    kafka_journey:R --> L:worker
    worker:B --> T:neo4j
    neo4j:R --> L:analytics
    analytics:B --> T:redis
    redis:R --> L:enforcer
