name: "Credential Stuffing Attack"
description: "Demonstrates abuse detection: Multiple IPs trying many user accounts using stolen credentials"

metadata:
  attack_type: "credential_stuffing"
  severity: "critical"

  # Attack pattern definition
  pattern:
    description: "Distributed attack using stolen credentials across multiple IPs and user accounts"
    behavior:
      - "Attacker obtains stolen username/password pairs from data breach"
      - "Uses multiple IPs (proxy network/botnet) to distribute attack"
      - "Tests credentials against many user accounts"
      - "Low velocity per IP to avoid rate limiting"
      - "Some successful logins if credentials are valid"
    indicators:
      - "Multiple IPs attempting auth on different user accounts"
      - "Failed auth attempts across many users"
      - "Mix of failed and successful auth (valid stolen credentials)"
      - "Bot-like user agents from residential proxies"
      - "Geographic distribution of IPs (VPN/proxy networks)"

  # Detection rules (what to look for in graph)
  detection_rules:
    IPAddress:
      - pattern: "Multiple IPs each trying different user accounts"
        query_hint: "MATCH (e:Event)-[:ORIGINATED_FROM]->(ip:IPAddress) WHERE e.action = 'auth_token_validated' WITH ip, collect(DISTINCT e.user_id) as users WHERE size(users) > 3"

    User:
      - pattern: "User accounts targeted from multiple IPs"
        query_hint: "MATCH (e:Event)-[:PERFORMED_BY]->(u:User) WHERE e.status = 'fail' WITH u, collect(DISTINCT e.client_ip) as ips WHERE size(ips) > 1"

    Event:
      - pattern: "Failed auth attempts distributed across IPs and users"
        query_hint: "MATCH (e:Event {action: 'auth_token_validated', status: 'fail'}) RETURN count(DISTINCT e.client_ip), count(DISTINCT e.user_id)"

# Fixture generation configuration
fixture_config:
  # Time range for generated events
  time_range:
    start: "2025-12-29T14:00:00Z"
    end: "2025-12-29T16:00:00Z"
    duration_hours: 2

  # Number of credential stuffing campaigns
  campaigns: 1

  # Total events to generate
  total_events:
    min: 50
    max: 100

  # Stores to target
  stores:
    - id: "store-1"
      weight: 0.6  # 60% of attacks
    - id: "store-2"
      weight: 0.3  # 30% of attacks
    - id: "store-3"
      weight: 0.1  # 10% of attacks

  # Attacker IPs (proxy network / botnet)
  attacker_ips:
    - address: "45.142.212.100"
      location: "Netherlands (VPN)"
      type: "residential_proxy"
    - address: "194.36.25.45"
      location: "Germany (Datacenter)"
      type: "datacenter_proxy"
    - address: "103.89.234.12"
      location: "Singapore (VPN)"
      type: "vpn_exit"
    - address: "185.220.101.23"
      location: "France (Tor Exit)"
      type: "tor_exit"
    - address: "167.172.45.89"
      location: "USA (Cloud VPS)"
      type: "cloud_vps"
    - address: "91.235.116.34"
      location: "Russia (Residential)"
      type: "residential_proxy"
    - address: "203.0.113.45"
      location: "Unknown (Suspicious)"
      type: "bot"

  # Targeted user accounts (from stolen credential database)
  target_users:
    - user_id: 2001
      email: "john.smith@gmail.com"
      password: "Summer2023!"  # Stolen credential
      valid: true  # Credential is valid
    - user_id: 2002
      email: "sarah.jones@yahoo.com"
      password: "P@ssw0rd123"
      valid: false  # Password changed since breach
    - user_id: 2003
      email: "mike.wilson@outlook.com"
      password: "MyDog2022"
      valid: true  # Valid credential
    - user_id: 2004
      email: "lisa.brown@hotmail.com"
      password: "Welcome1!"
      valid: false  # Account locked
    - user_id: 2005
      email: "david.taylor@gmail.com"
      password: "qwerty123"
      valid: false
    - user_id: 2006
      email: "emma.davis@icloud.com"
      password: "Letmein99"
      valid: true  # Valid credential
    - user_id: 2007
      email: "james.miller@proton.me"
      password: "Admin123"
      valid: false
    - user_id: 2008
      email: "olivia.moore@gmail.com"
      password: "Football2023"
      valid: false
    - user_id: 2009
      email: "william.anderson@yahoo.com"
      password: "Dragon2024"
      valid: false
    - user_id: 2010
      email: "sophia.thomas@outlook.com"
      password: "Monkey123!"
      valid: true  # Valid credential

  # Device types and user agents (mix of bots and residential proxies)
  devices:
    - device_type: "web"
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      type: "residential_proxy"
      weight: 0.3
    - device_type: "web"
      user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/537.36"
      type: "residential_proxy"
      weight: 0.2
    - device_type: "mobile"
      user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)"
      type: "mobile_proxy"
      weight: 0.15
    - device_type: "web"
      user_agent: "Python-Requests/2.28.1"
      type: "bot"
      weight: 0.15
    - device_type: "web"
      user_agent: "curl/7.68.0"
      type: "bot"
      weight: 0.1
    - device_type: "mobile"
      user_agent: "Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36"
      type: "mobile_proxy"
      weight: 0.1

  # Query string generation (for URL query parameters)
  query_generation:
    enabled: true
    probability: 0.2  # 20% of events will have query strings (1 in 5)
    templates:
      auth_token_validated:
        - "?redirect=/books"
        - "?remember=true"
        - "?client_version=2.1.0"
        - "?device_id=abc123"
      view_books:
        - "?page=1"
        - "?sort=popular"
        - "?category=all"
      add_to_cart:
        - "?quantity=1"
        - "?wishlist=false"

# Credential stuffing scenarios
scenarios:
  # Campaign 1: Distributed credential stuffing attack
  - name: "Credential Stuffing Campaign #1"
    description: "Attackers test stolen credentials from multiple IPs"

    # Attack timeline
    events:
      # IP 1 tries user 2001
      - timestamp_offset_minutes: 0
        client_ip: "45.142.212.100"
        user_id: 2001
        email: "john.smith@gmail.com"
        device_type: "web"
        user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        action: "auth_token_validated"
        status: "pass"  # Valid stolen credential
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        query: "?redirect=/books&remember=true"
        description: "SUCCESSFUL credential stuffing - stolen credential works"

      # IP 2 tries user 2002
      - timestamp_offset_minutes: 1
        client_ip: "194.36.25.45"
        user_id: 2002
        email: "sarah.jones@yahoo.com"
        device_type: "web"
        user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/537.36"
        action: "auth_token_validated"
        status: "fail"  # Password changed
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        description: "Failed - password changed since breach"

      # IP 3 tries user 2003
      - timestamp_offset_minutes: 2
        client_ip: "103.89.234.12"
        user_id: 2003
        email: "mike.wilson@outlook.com"
        device_type: "mobile"
        user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)"
        action: "auth_token_validated"
        status: "pass"  # Valid stolen credential
        store_id: "store-2"
        path: "/api/v1/store-2/auth/validate"
        description: "SUCCESSFUL credential stuffing"

      # IP 4 tries user 2004
      - timestamp_offset_minutes: 3
        client_ip: "185.220.101.23"
        user_id: 2004
        email: "lisa.brown@hotmail.com"
        device_type: "web"
        user_agent: "Python-Requests/2.28.1"
        action: "auth_token_validated"
        status: "fail"  # Account locked
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        description: "Failed - account locked"

      # IP 1 tries user 2005 (same IP, different user)
      - timestamp_offset_minutes: 5
        client_ip: "45.142.212.100"
        user_id: 2005
        email: "david.taylor@gmail.com"
        device_type: "web"
        user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        action: "auth_token_validated"
        status: "fail"
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        description: "Same IP trying different user"

      # IP 5 tries user 2006
      - timestamp_offset_minutes: 7
        client_ip: "167.172.45.89"
        user_id: 2006
        email: "emma.davis@icloud.com"
        device_type: "web"
        user_agent: "curl/7.68.0"
        action: "auth_token_validated"
        status: "pass"  # Valid stolen credential
        store_id: "store-3"
        path: "/api/v1/store-3/auth/validate"
        description: "SUCCESSFUL credential stuffing from cloud VPS"

      # IP 6 tries user 2007
      - timestamp_offset_minutes: 10
        client_ip: "91.235.116.34"
        user_id: 2007
        email: "james.miller@proton.me"
        device_type: "mobile"
        user_agent: "Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36"
        action: "auth_token_validated"
        status: "fail"
        store_id: "store-2"
        path: "/api/v1/store-2/auth/validate"
        description: "Failed attempt from residential proxy"

      # IP 2 tries user 2008 (same IP, different user)
      - timestamp_offset_minutes: 12
        client_ip: "194.36.25.45"
        user_id: 2008
        email: "olivia.moore@gmail.com"
        device_type: "web"
        user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/537.36"
        action: "auth_token_validated"
        status: "fail"
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        description: "Same IP trying different user"

      # IP 7 tries user 2009
      - timestamp_offset_minutes: 15
        client_ip: "203.0.113.45"
        user_id: 2009
        email: "william.anderson@yahoo.com"
        device_type: "web"
        user_agent: "Python-Requests/2.28.1"
        action: "auth_token_validated"
        status: "fail"
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        description: "Bot attempting credential stuffing"

      # IP 3 tries user 2010 (same IP, different user)
      - timestamp_offset_minutes: 18
        client_ip: "103.89.234.12"
        user_id: 2010
        email: "sophia.thomas@outlook.com"
        device_type: "mobile"
        user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)"
        action: "auth_token_validated"
        status: "pass"  # Valid stolen credential
        store_id: "store-2"
        path: "/api/v1/store-2/auth/validate"
        description: "SUCCESSFUL credential stuffing"

      # Successful login followed by malicious activity
      - timestamp_offset_minutes: 20
        client_ip: "45.142.212.100"
        user_id: 2001
        email: "john.smith@gmail.com"
        device_type: "web"
        session_id: "01963852-f5g6-8d6c-c1h5-9g0e7f6g5h5c"
        auth_token_id: "token_compromised_2001"
        action: "view_books"
        store_id: "store-1"
        path: "/api/v1/store-1/books"
        query: "?category=all&sort=popular"
        description: "Attacker using compromised account"

      # Attacker adds items to cart
      - timestamp_offset_minutes: 22
        client_ip: "45.142.212.100"
        user_id: 2001
        email: "john.smith@gmail.com"
        device_type: "web"
        session_id: "01963852-f5g6-8d6c-c1h5-9g0e7f6g5h5c"
        auth_token_id: "token_compromised_2001"
        action: "add_to_cart"
        store_id: "store-1"
        path: "/api/v1/store-1/cart/add"
        description: "Fraudulent cart activity"

# Expected Neo4j graph structure
expected_graph:
  nodes:
    Event:
      count: "~60-100"
      key_properties:
        - event_id
        - action
        - status
        - timestamp
        - client_ip
        - user_id
        - email
        - device_type
        - store_id

    IPAddress:
      count: 7  # Multiple attacker IPs
      suspicious_pattern: "Each IP tries multiple user accounts"

    User:
      count: 10  # Target user accounts
      suspicious_pattern: "Users targeted from multiple IPs"

    Store:
      count: 3

  relationships:
    ORIGINATED_FROM:
      pattern: "Events → IPAddress (distributed across many IPs)"
      count: "~60-100"

    PERFORMED_BY:
      pattern: "Events → User (many users targeted)"
      count: "~60-100"

    TARGETED_STORE:
      pattern: "Events → Store"
      count: "~60-100"

# Abuse detection queries
abuse_assertions:
  - name: "Detect multiple IPs targeting multiple users"
    query: |
      MATCH (e:Event {action: 'auth_token_validated'})
      WHERE e.timestamp > datetime() - duration('PT2H')
      WITH count(DISTINCT e.client_ip) as ip_count,
          count(DISTINCT e.user_id) as user_count,
          count(e) as total_attempts
      RETURN ip_count, user_count, total_attempts
    expected_result_count: 1
    description: "Should show distributed attack across multiple IPs and users"

  - name: "Detect IPs trying multiple user accounts"
    query: |
      MATCH (e:Event {action: 'auth_token_validated'})-[:ORIGINATED_FROM]->(ip:IPAddress)
      WHERE e.timestamp > datetime() - duration('PT2H')
      WITH ip.address as ip_address,
          collect(DISTINCT e.user_id) as targeted_users,
          count(e) as attempts
      WHERE size(targeted_users) > 1
      RETURN ip_address, targeted_users, size(targeted_users) as user_count, attempts
      ORDER BY user_count DESC
    expected_result_count: ">= 3"
    description: "Should find IPs targeting multiple user accounts"

  - name: "Detect users targeted from multiple IPs"
    query: |
      MATCH (e:Event {action: 'auth_token_validated'})-[:PERFORMED_BY]->(u:User)
      WHERE e.timestamp > datetime() - duration('PT2H')
      WITH u.user_id as user_id,
          collect(DISTINCT e.client_ip) as attacker_ips,
          count(e) as attempts
      WHERE size(attacker_ips) > 1
      RETURN user_id, attacker_ips, size(attacker_ips) as ip_count, attempts
      ORDER BY ip_count DESC
    expected_result_count: ">= 2"
    description: "Should find users targeted from multiple IPs"

  - name: "Detect successful credential stuffing"
    query: |
      MATCH (e:Event {action: 'auth_token_validated', status: 'pass'})-[:ORIGINATED_FROM]->(ip:IPAddress)
      WHERE e.timestamp > datetime() - duration('PT2H')
        AND NOT ip.address STARTS WITH '192.168'  # Exclude internal IPs
      RETURN ip.address, e.user_id, e.timestamp, e.email
      ORDER BY e.timestamp
    expected_result_count: ">= 3"
    description: "Should detect successful logins from suspicious IPs"

  - name: "Calculate credential stuffing success rate"
    query: |
      MATCH (e:Event {action: 'auth_token_validated'})
      WHERE e.timestamp > datetime() - duration('PT2H')
      WITH count(CASE WHEN e.status = 'pass' THEN 1 END) as successful,
          count(CASE WHEN e.status = 'fail' THEN 1 END) as failed,
          count(e) as total
      RETURN successful, failed, total,
             round(100.0 * successful / total, 2) as success_rate_percent
    expected_result_count: 1
    description: "Should calculate attack success rate (valid stolen credentials)"

# Python fixture generator hints
generator_config:
  strategy: "scenario_based"

  # How to generate timestamps
  timestamp_generation:
    method: "offset_based"
    base_time: "${fixture_config.time_range.start}"
    jitter_seconds: 3

  # How to generate event_ids
  event_id_generation:
    method: "uuid_v7"

  # Additional events to add (noise)
  noise_events:
    enabled: true
    count: 50
    description: "Add more failed attempts from same IPs to different users"

  # Validation
  validation:
    - check: "Multiple IPs in dataset"
    - check: "Multiple users targeted"
    - check: "Mix of pass and fail statuses"
    - check: "Some IPs try multiple users"
    - check: "Some users targeted from multiple IPs"

# Output format
output:
  format: "json"
  file: "credential-stuffing-events.json"

  # Event structure (maps to Neo4j v2.0 model)
  event_schema:
    event_id: "string (UUID v7)"
    action: "string"
    status: "string (pass/fail)"
    timestamp: "string (ISO 8601)"
    client_ip: "string"
    user_agent: "string"
    device_type: "string"
    path: "string"
    query: "string | null"
    session_id: "string (UUID v7) | null"
    user_id: "integer"
    email: "string"
    store_id: "string"
    auth_token_id: "string | null"
    data: "json | null"
