name: "Authentication Token Abuse"
description: "Demonstrates abuse detection: Auth tokens being shared, sold, or abused across multiple users and IPs"

metadata:
  attack_type: "token_abuse"
  severity: "critical"

  # Attack pattern definition
  pattern:
    description: "Single authentication token used abnormally across multiple users, IPs, or in excessive volume"
    behavior:
      - "User authenticates and obtains auth token"
      - "Token is shared/sold to other users"
      - "Same token used from many different IP addresses"
      - "Token used for excessive number of requests (rate abuse)"
      - "Token used simultaneously from multiple geographic locations"
      - "Token continues to be used after logout"
    indicators:
      - "Same auth_token_id from 5+ different IP addresses"
      - "Same auth_token_id with 100+ events in short time"
      - "Auth token used by multiple user_id values"
      - "Geographic impossibility (same token in NYC and China simultaneously)"
      - "Token used after logout event"
      - "Suspicious user agents for token (bots, scrapers)"

  # Detection rules (what to look for in graph)
  detection_rules:
    Event:
      - pattern: "auth_token_id used from many IPs"
        query_hint: "MATCH (e:Event) WHERE e.auth_token_id IS NOT NULL WITH e.auth_token_id as token, collect(DISTINCT e.client_ip) as ips WHERE size(ips) >= 5"

    IPAddress:
      - pattern: "Same token from geographically distant IPs"
        query_hint: "MATCH (e:Event)-[:ORIGINATED_FROM]->(ip:IPAddress) WHERE e.auth_token_id IS NOT NULL GROUP BY e.auth_token_id"

    User:
      - pattern: "Multiple users sharing same token"
        query_hint: "MATCH (e:Event)-[:PERFORMED_BY]->(u:User) WHERE e.auth_token_id IS NOT NULL WITH e.auth_token_id as token, collect(DISTINCT u.user_id) as users WHERE size(users) > 1"

# Fixture generation configuration
fixture_config:
  # Time range for generated events
  time_range:
    start: "2025-12-29T20:00:00Z"
    end: "2025-12-29T22:00:00Z"
    duration_hours: 2

  # Stores to target
  stores:
    - id: "store-1"
      weight: 0.7
    - id: "store-2"
      weight: 0.3

  # Endpoints/actions
  endpoints:
    - path: "/api/v1/{store}/books"
      action: "view_books"
      weight: 0.4
    - path: "/api/v1/{store}/books/{id}"
      action: "view_book_detail"
      weight: 0.2
    - path: "/api/v1/{store}/search"
      action: "search"
      weight: 0.2
    - path: "/api/v1/{store}/cart/add"
      action: "add_to_cart"
      weight: 0.1
    - path: "/api/v1/{store}/orders"
      action: "view_orders"
      weight: 0.1

  # User accounts
  users:
    - user_id: 6001
      email: "original.user@example.com"
      legitimate: true
    - user_id: 6002
      email: "token.buyer1@example.com"
      legitimate: false
    - user_id: 6003
      email: "token.buyer2@example.com"
      legitimate: false
    - user_id: 6004
      email: "token.buyer3@example.com"
      legitimate: false
    - user_id: 6005
      email: "token.buyer4@example.com"
      legitimate: false
    - user_id: 6006
      email: "rate.abuser@example.com"
      legitimate: false

  # IP addresses (geographically diverse for token sharing)
  ip_addresses:
    # Original user IP
    - address: "192.168.1.50"
      location: "Boston, US"
      type: "home_broadband"
      legitimate: true
    # Token buyers/sharers from different locations
    - address: "203.0.113.10"
      location: "Moscow, Russia"
      type: "vpn"
      legitimate: false
    - address: "198.51.100.20"
      location: "Beijing, China"
      type: "proxy"
      legitimate: false
    - address: "185.220.101.30"
      location: "Berlin, Germany"
      type: "tor_exit"
      legitimate: false
    - address: "45.142.212.40"
      location: "Amsterdam, Netherlands"
      type: "datacenter"
      legitimate: false
    - address: "103.89.234.50"
      location: "Singapore"
      type: "cloud_vps"
      legitimate: false
    - address: "91.235.116.60"
      location: "London, UK"
      type: "residential_proxy"
      legitimate: false
    - address: "167.172.45.70"
      location: "New York, US (VPS)"
      type: "cloud_vps"
      legitimate: false

  # Devices
  devices:
    - device_type: "web"
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      weight: 0.3
    - device_type: "mobile"
      user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)"
      weight: 0.2
    - device_type: "api"
      user_agent: "Python-Requests/2.31.0"
      weight: 0.2
    - device_type: "api"
      user_agent: "curl/7.88.0"
      weight: 0.15
    - device_type: "web"
      user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36"
      weight: 0.15

  # Query string generation
  query_generation:
    enabled: true
    probability: 0.2
    templates:
      view_books:
        - "?page=1"
        - "?sort=popular"
        - "?category=all"
      search:
        - "?q=fiction"
        - "?q=programming"
        - "?q=bestsellers"

# Token abuse scenarios
scenarios:
  # Scenario 1: Shared/sold token used from many IPs
  - name: "Token Sharing - Distributed Abuse"
    auth_token_id: "token_shared_premium_6001"
    description: "Premium user's token is shared/sold and used from 7 different countries"

    events:
      # Original user authenticates (Boston)
      - timestamp_offset_minutes: 0
        user_id: 6001
        email: "original.user@example.com"
        client_ip: "192.168.1.50"
        device_type: "web"
        session_id: "01963852-a1b2-c3d4-e5f6-111111111111"
        action: "auth_token_validated"
        status: "pass"
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        description: "Original user authenticates in Boston"

      - timestamp_offset_minutes: 1
        user_id: 6001
        client_ip: "192.168.1.50"
        device_type: "web"
        session_id: "01963852-a1b2-c3d4-e5f6-111111111111"
        action: "view_books"
        store_id: "store-1"
        path: "/api/v1/store-1/books"
        description: "Normal usage"

      # Token used from Moscow (5 mins later - possible but suspicious)
      - timestamp_offset_minutes: 5
        user_id: 6002
        email: "token.buyer1@example.com"
        client_ip: "203.0.113.10"
        device_type: "web"
        session_id: "01963852-b2c3-d4e5-f6a7-222222222222"
        action: "view_books"
        store_id: "store-1"
        path: "/api/v1/store-1/books"
        description: "⚠️ ABUSE: Different user using shared token from Moscow"

      # Token used from Beijing (same time as Moscow - impossible)
      - timestamp_offset_minutes: 6
        user_id: 6003
        email: "token.buyer2@example.com"
        client_ip: "198.51.100.20"
        device_type: "mobile"
        session_id: "01963852-c3d4-e5f6-a7b8-333333333333"
        action: "search"
        store_id: "store-1"
        path: "/api/v1/store-1/search"
        query: "?q=fiction"
        description: "⚠️ ABUSE: Third user with shared token from Beijing"

      # Token from Berlin
      - timestamp_offset_minutes: 8
        user_id: 6004
        email: "token.buyer3@example.com"
        client_ip: "185.220.101.30"
        device_type: "web"
        session_id: "01963852-d4e5-f6a7-b8c9-444444444444"
        action: "view_book_detail"
        store_id: "store-1"
        path: "/api/v1/store-1/books/456"
        description: "⚠️ ABUSE: Shared token from Berlin (Tor)"

      # Token from Amsterdam
      - timestamp_offset_minutes: 10
        user_id: 6005
        email: "token.buyer4@example.com"
        client_ip: "45.142.212.40"
        device_type: "api"
        user_agent: "Python-Requests/2.31.0"
        session_id: "01963852-e5f6-a7b8-c9d0-555555555555"
        action: "view_books"
        store_id: "store-2"
        path: "/api/v1/store-2/books"
        description: "⚠️ ABUSE: Shared token from Amsterdam datacenter"

      # Token from Singapore
      - timestamp_offset_minutes: 12
        user_id: 6002
        client_ip: "103.89.234.50"
        device_type: "web"
        session_id: "01963852-f6a7-b8c9-d0e1-666666666666"
        action: "view_orders"
        store_id: "store-1"
        path: "/api/v1/store-1/orders"
        description: "⚠️ ABUSE: Shared token from Singapore"

      # Token from London
      - timestamp_offset_minutes: 15
        user_id: 6003
        client_ip: "91.235.116.60"
        device_type: "mobile"
        session_id: "01963852-a7b8-c9d0-e1f2-777777777777"
        action: "view_books"
        store_id: "store-1"
        path: "/api/v1/store-1/books"
        description: "⚠️ ABUSE: Shared token from London"

      # Token from NYC VPS
      - timestamp_offset_minutes: 18
        user_id: 6004
        client_ip: "167.172.45.70"
        device_type: "api"
        session_id: "01963852-b8c9-d0e1-f2a3-888888888888"
        action: "search"
        store_id: "store-1"
        path: "/api/v1/store-1/search"
        query: "?q=programming"
        description: "⚠️ ABUSE: Shared token from NYC cloud VPS"

  # Scenario 2: Rate abuse - excessive requests with same token
  - name: "Token Rate Abuse"
    auth_token_id: "token_rate_abuser_6006"
    description: "Single token used for excessive API requests (scraping/automation)"

    events:
      # User authenticates
      - timestamp_offset_minutes: 30
        user_id: 6006
        email: "rate.abuser@example.com"
        client_ip: "45.142.212.40"
        device_type: "api"
        user_agent: "Python-Requests/2.31.0"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "auth_token_validated"
        status: "pass"
        store_id: "store-1"
        path: "/api/v1/store-1/auth/validate"
        description: "Bot authenticates"

      # Rapid-fire requests (every 30 seconds for next 10 minutes)
      # Request 1
      - timestamp_offset_minutes: 31
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "view_books"
        store_id: "store-1"
        path: "/api/v1/store-1/books"
        description: "Rate abuse: Request 1"

      - timestamp_offset_minutes: 31
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "search"
        store_id: "store-1"
        path: "/api/v1/store-1/search"
        description: "Rate abuse: Request 2"

      - timestamp_offset_minutes: 32
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "view_books"
        store_id: "store-2"
        path: "/api/v1/store-2/books"
        description: "Rate abuse: Request 3"

      - timestamp_offset_minutes: 32
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "search"
        store_id: "store-2"
        path: "/api/v1/store-2/search"
        description: "Rate abuse: Request 4"

      - timestamp_offset_minutes: 33
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "view_book_detail"
        store_id: "store-1"
        path: "/api/v1/store-1/books/100"
        description: "Rate abuse: Request 5"

      - timestamp_offset_minutes: 33
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "view_book_detail"
        store_id: "store-1"
        path: "/api/v1/store-1/books/101"
        description: "Rate abuse: Request 6"

      - timestamp_offset_minutes: 34
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "view_book_detail"
        store_id: "store-1"
        path: "/api/v1/store-1/books/102"
        description: "Rate abuse: Request 7"

      - timestamp_offset_minutes: 34
        user_id: 6006
        client_ip: "45.142.212.40"
        device_type: "api"
        session_id: "01963852-c9d0-e1f2-a3b4-999999999999"
        action: "view_book_detail"
        store_id: "store-1"
        path: "/api/v1/store-1/books/103"
        description: "Rate abuse: Request 8"

# Expected Neo4j graph structure
expected_graph:
  nodes:
    Event:
      count: "~50-80"
      key_properties:
        - event_id
        - action
        - timestamp
        - auth_token_id
        - client_ip
        - user_id

    Session:
      count: "~10-15"
      suspicious_pattern: "Multiple sessions sharing same auth_token_id"

    User:
      count: 6
      suspicious_pattern: "Multiple users sharing same auth_token_id"

    IPAddress:
      count: 8
      suspicious_pattern: "Same auth_token_id from 7+ different IPs"

    Store:
      count: 2

  relationships:
    ORIGINATED_FROM:
      pattern: "Events → IPAddress (same token from many IPs)"
      count: "~50-80"

    PERFORMED_BY:
      pattern: "Events → User (same token used by multiple users)"
      count: "~50-80"

    IN_SESSION:
      pattern: "Events → Session (many sessions per token)"
      count: "~50-80"

# Abuse detection queries
abuse_assertions:
  - name: "Detect tokens used from many IPs"
    query: |
      MATCH (e:Event)-[:ORIGINATED_FROM]->(ip:IPAddress)
      WHERE e.auth_token_id IS NOT NULL
      WITH e.auth_token_id as token,
          collect(DISTINCT ip.address) as ips
      WHERE size(ips) >= 5
      RETURN token, ips, size(ips) as ip_count
      ORDER BY ip_count DESC
    expected_result_count: ">= 1"
    description: "Should find tokens used from 5+ different IP addresses"

  - name: "Detect tokens shared by multiple users"
    query: |
      MATCH (e:Event)-[:PERFORMED_BY]->(u:User)
      WHERE e.auth_token_id IS NOT NULL
      WITH e.auth_token_id as token,
          collect(DISTINCT u.user_id) as user_ids,
          collect(DISTINCT u.email) as emails
      WHERE size(user_ids) > 1
      RETURN token, user_ids, emails, size(user_ids) as user_count
      ORDER BY user_count DESC
    expected_result_count: ">= 1"
    description: "Should find tokens used by multiple different users"

  - name: "Detect rate abuse (high event count per token)"
    query: |
      MATCH (e:Event)
      WHERE e.auth_token_id IS NOT NULL
        AND e.timestamp > datetime() - duration('PT1H')
      WITH e.auth_token_id as token,
          count(e) as event_count
      WHERE event_count >= 8
      RETURN token, event_count
      ORDER BY event_count DESC
    expected_result_count: ">= 1"
    description: "Should find tokens with 8+ events in last hour (rate abuse)"

  - name: "Detect geographic impossibility"
    query: |
      MATCH (e:Event)-[:ORIGINATED_FROM]->(ip:IPAddress)
      WHERE e.auth_token_id IS NOT NULL
      WITH e.auth_token_id as token,
          e.timestamp as timestamp,
          ip.address as ip_address
      ORDER BY token, timestamp
      WITH token, collect({time: timestamp, ip: ip_address}) as events
      WHERE size(events) >= 5
      RETURN token, events, size(events) as location_count
      ORDER BY location_count DESC
    expected_result_count: ">= 1"
    description: "Should find tokens used from multiple geographic locations"

  - name: "Calculate token abuse severity score"
    query: |
      MATCH (e:Event)
      WHERE e.auth_token_id IS NOT NULL
      WITH e.auth_token_id as token,
          count(DISTINCT e.client_ip) as ip_count,
          count(DISTINCT e.user_id) as user_count,
          count(e) as total_events
      WITH token, ip_count, user_count, total_events,
           (ip_count * 2) + (user_count * 3) + (total_events / 10) as abuse_score
      WHERE abuse_score >= 10
      RETURN token, ip_count, user_count, total_events,
            round(abuse_score) as abuse_score
      ORDER BY abuse_score DESC
    expected_result_count: ">= 1"
    description: "Should calculate abuse severity scores for tokens"

# Python fixture generator hints
generator_config:
  strategy: "scenario_based"

  # How to generate timestamps
  timestamp_generation:
    method: "offset_based"
    base_time: "${fixture_config.time_range.start}"
    jitter_seconds: 2

  # How to generate event_ids
  event_id_generation:
    method: "uuid_v7"

  # Additional events to add (noise)
  noise_events:
    enabled: true
    count: 60
    description: "Add legitimate token usage from single-user, single-IP tokens"

  # Validation
  validation:
    - check: "Some auth_token_id values used from multiple IPs"
    - check: "Some auth_token_id values used by multiple users"
    - check: "High event count for rate abuse tokens"

# Output format
output:
  format: "json"
  file: "token-abuse-events.json"

  # Event structure (maps to Neo4j v2.0 model)
  event_schema:
    event_id: "string (UUID v7)"
    action: "string"
    status: "string | null"
    timestamp: "string (ISO 8601)"
    client_ip: "string"
    user_agent: "string"
    device_type: "string"
    path: "string"
    query: "string | null"
    session_id: "string (UUID v7)"
    user_id: "integer"
    email: "string | null"
    store_id: "string"
    auth_token_id: "string"
    data: "json | null"
    archived: "boolean"
